language: ruby

rvm:
  - 2.5.0
env:
  - DB=mysql
  - DB=postgresql

install: bundle install --jobs=3 --retry=3

before_script: bundle exec rake setup_db # creates the database used for tests

sudo: false

# using default travis command
### script: bundle exec rake
