language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  
env:
  - DB=mysql
  - DB=postgresql

before_script: rake setup_dummy_app # creates the database used for tests

# using default travis command
### script: bundle exec rake
