language: ruby

rvm:
  - 2.2.5
env:
  - DB=mysql
  - DB=postgresql

services:
  - mysql
  - postgres

before_script: rake setup_db # creates the database used for tests

sudo: false

install: bundle install --jobs=3 --retry=3

# using default travis command
### script: bundle exec rake
