language: ruby

rvm:
  - 2.5.0
env:
  - DB=mysql
  - DB=postgresql

before_script: rake setup_db # creates the database used for tests

sudo: false

# using default travis command
### script: bundle exec rake
