language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  
env:
  - DB=mysql
  - DB=postgresql

before_script:
  - DISABLE_MIGRATE=true DISABLE_CREATE=true rake dummy:app
  - rm spec/dummy/config/database.yml
  - cp spec/support/database.txt spec/dummy/config/database.yml
  - cd spec/dummy && rake db:create && cd ../..
  - cd spec/dummy && rails g qe:install && rake db:test:prepare && cd ../..

# using default travis command
### script: bundle exec rake
