mysql: &mysql
  adapter: mysql<%= "2" unless ( ENV["TRAVIS_RUBY_VERSION"].include? "j" if ENV["TRAVIS_RUBY_VERSION"] ) %>
  username: root
  password:

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  database: fe_dev
  <<: *defaults

test:
  database: fe_test
  <<: *defaults

production:
  database: fe_prod
  <<: *defaults
